/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createVenueDtoFromDiscriminatorValue, type VenueDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/venues
 */
export interface VenuesRequestBuilder extends BaseRequestBuilder<VenuesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VenueDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<VenuesRequestBuilderGetQueryParameters> | undefined) : Promise<VenueDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<VenuesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface VenuesRequestBuilderGetQueryParameters {
    cityId?: Guid;
    lat?: number;
    lng?: number;
    radiusKm?: number;
    sportId?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const VenuesRequestBuilderUriTemplate = "{+baseurl}/api/venues{?cityId*,lat*,lng*,radiusKm*,sportId*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const VenuesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VenuesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createVenueDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
