/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSportDtoFromDiscriminatorValue, type SportDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/sports
 */
export interface SportsRequestBuilder extends BaseRequestBuilder<SportsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SportDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SportDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SportsRequestBuilderUriTemplate = "{+baseurl}/api/sports";
/**
 * Metadata for all the requests in the request builder.
 */
export const SportsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SportsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSportDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
