/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithHandleItemRequestBuilder, WithHandleItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/users
 */
export interface UsersRequestBuilder extends BaseRequestBuilder<UsersRequestBuilder> {
    /**
     * Gets an item from the game-org-api-client.api.users.item collection
     * @param handle Unique identifier of the item
     * @returns {WithHandleItemRequestBuilder}
     */
     byHandle(handle: string) : WithHandleItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UsersRequestBuilderUriTemplate = "{+baseurl}/api/users";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UsersRequestBuilderNavigationMetadata: Record<Exclude<keyof UsersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byHandle: {
        requestsMetadata: WithHandleItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["handle"],
    },
};
/* tslint:enable */
/* eslint-enable */
