/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AuthRequestBuilderNavigationMetadata, type AuthRequestBuilder } from './auth/index.js';
// @ts-ignore
import { CitiesRequestBuilderRequestsMetadata, type CitiesRequestBuilder } from './cities/index.js';
// @ts-ignore
import { MeRequestBuilderNavigationMetadata, MeRequestBuilderRequestsMetadata, type MeRequestBuilder } from './me/index.js';
// @ts-ignore
import { SportsRequestBuilderRequestsMetadata, type SportsRequestBuilder } from './sports/index.js';
// @ts-ignore
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata } from './users/index.js';
// @ts-ignore
import { type VenuesRequestBuilder, VenuesRequestBuilderRequestsMetadata } from './venues/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The auth property
     */
    get auth(): AuthRequestBuilder;
    /**
     * The cities property
     */
    get cities(): CitiesRequestBuilder;
    /**
     * The me property
     */
    get me(): MeRequestBuilder;
    /**
     * The sports property
     */
    get sports(): SportsRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
    /**
     * The venues property
     */
    get venues(): VenuesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    auth: {
        navigationMetadata: AuthRequestBuilderNavigationMetadata,
    },
    cities: {
        requestsMetadata: CitiesRequestBuilderRequestsMetadata,
    },
    me: {
        requestsMetadata: MeRequestBuilderRequestsMetadata,
        navigationMetadata: MeRequestBuilderNavigationMetadata,
    },
    sports: {
        requestsMetadata: SportsRequestBuilderRequestsMetadata,
    },
    users: {
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
    venues: {
        requestsMetadata: VenuesRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
