/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPublicProfileDtoFromDiscriminatorValue, type PublicProfileDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/users/{handle}
 */
export interface WithHandleItemRequestBuilder extends BaseRequestBuilder<WithHandleItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PublicProfileDto>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PublicProfileDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithHandleItemRequestBuilderUriTemplate = "{+baseurl}/api/users/{handle}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithHandleItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithHandleItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createPublicProfileDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
