/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCityDtoFromDiscriminatorValue, type CityDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/cities
 */
export interface CitiesRequestBuilder extends BaseRequestBuilder<CitiesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CityDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CityDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CitiesRequestBuilderUriTemplate = "{+baseurl}/api/cities";
/**
 * Metadata for all the requests in the request builder.
 */
export const CitiesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CitiesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createCityDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
