/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type DateOnly, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AuthResponseDto extends AdditionalDataHolder, Parsable {
    /**
     * The displayName property
     */
    displayName?: string | null;
    /**
     * The handle property
     */
    handle?: string | null;
    /**
     * The userId property
     */
    userId?: Guid | null;
}
export interface CityDto extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lat property
     */
    lat?: number | null;
    /**
     * The lng property
     */
    lng?: number | null;
    /**
     * The nameI18n property
     */
    nameI18n?: CityDto_nameI18n | null;
    /**
     * The slug property
     */
    slug?: string | null;
}
export interface CityDto_nameI18n extends AdditionalDataHolder, Parsable {
}
export interface CityDto2 extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lat property
     */
    lat?: number | null;
    /**
     * The lng property
     */
    lng?: number | null;
    /**
     * The nameI18n property
     */
    nameI18n?: CityDto2_nameI18n | null;
    /**
     * The slug property
     */
    slug?: string | null;
}
export interface CityDto2_nameI18n extends AdditionalDataHolder, Parsable {
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthResponseDto}
 */
// @ts-ignore
export function createAuthResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CityDto_nameI18n}
 */
// @ts-ignore
export function createCityDto_nameI18nFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCityDto_nameI18n;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CityDto2_nameI18n}
 */
// @ts-ignore
export function createCityDto2_nameI18nFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCityDto2_nameI18n;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CityDto2}
 */
// @ts-ignore
export function createCityDto2FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCityDto2;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CityDto}
 */
// @ts-ignore
export function createCityDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCityDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MeProfileDto}
 */
// @ts-ignore
export function createMeProfileDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMeProfileDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicProfileDto}
 */
// @ts-ignore
export function createPublicProfileDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicProfileDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicUserSportDto}
 */
// @ts-ignore
export function createPublicUserSportDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicUserSportDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SportDto_nameI18n}
 */
// @ts-ignore
export function createSportDto_nameI18nFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSportDto_nameI18n;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SportDto}
 */
// @ts-ignore
export function createSportDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSportDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TelegramAuthPayload}
 */
// @ts-ignore
export function createTelegramAuthPayloadFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTelegramAuthPayload;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateMeRequest}
 */
// @ts-ignore
export function createUpdateMeRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateMeRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpsertUserSportRequest}
 */
// @ts-ignore
export function createUpsertUserSportRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsertUserSportRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserSportDto}
 */
// @ts-ignore
export function createUserSportDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserSportDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserSportPositionDto}
 */
// @ts-ignore
export function createUserSportPositionDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserSportPositionDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {VenueDto}
 */
// @ts-ignore
export function createVenueDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVenueDto;
}
/**
 * The deserialization information for the current model
 * @param AuthResponseDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthResponseDto(authResponseDto: Partial<AuthResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "displayName": n => { authResponseDto.displayName = n.getStringValue(); },
        "handle": n => { authResponseDto.handle = n.getStringValue(); },
        "userId": n => { authResponseDto.userId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CityDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCityDto(cityDto: Partial<CityDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { cityDto.id = n.getGuidValue(); },
        "lat": n => { cityDto.lat = n.getNumberValue(); },
        "lng": n => { cityDto.lng = n.getNumberValue(); },
        "nameI18n": n => { cityDto.nameI18n = n.getObjectValue<CityDto_nameI18n>(createCityDto_nameI18nFromDiscriminatorValue); },
        "slug": n => { cityDto.slug = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CityDto_nameI18n The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCityDto_nameI18n(cityDto_nameI18n: Partial<CityDto_nameI18n> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param CityDto2 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCityDto2(cityDto2: Partial<CityDto2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { cityDto2.id = n.getGuidValue(); },
        "lat": n => { cityDto2.lat = n.getNumberValue(); },
        "lng": n => { cityDto2.lng = n.getNumberValue(); },
        "nameI18n": n => { cityDto2.nameI18n = n.getObjectValue<CityDto2_nameI18n>(createCityDto2_nameI18nFromDiscriminatorValue); },
        "slug": n => { cityDto2.slug = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CityDto2_nameI18n The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCityDto2_nameI18n(cityDto2_nameI18n: Partial<CityDto2_nameI18n> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param MeProfileDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMeProfileDto(meProfileDto: Partial<MeProfileDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "avatarId": n => { meProfileDto.avatarId = n.getGuidValue(); },
        "bio": n => { meProfileDto.bio = n.getStringValue(); },
        "birthDate": n => { meProfileDto.birthDate = n.getDateOnlyValue(); },
        "city": n => { meProfileDto.city = n.getObjectValue<CityDto>(createCityDtoFromDiscriminatorValue); },
        "displayName": n => { meProfileDto.displayName = n.getStringValue(); },
        "gender": n => { meProfileDto.gender = n.getEnumValue<NullableOfGender>(NullableOfGenderObject); },
        "handle": n => { meProfileDto.handle = n.getStringValue(); },
        "id": n => { meProfileDto.id = n.getGuidValue(); },
        "isVerified": n => { meProfileDto.isVerified = n.getBooleanValue(); },
        "locale": n => { meProfileDto.locale = n.getStringValue(); },
        "phone": n => { meProfileDto.phone = n.getStringValue(); },
        "profileVisibility": n => { meProfileDto.profileVisibility = n.getEnumValue<Visibility>(VisibilityObject); },
        "sports": n => { meProfileDto.sports = n.getCollectionOfObjectValues<UserSportDto>(createUserSportDtoFromDiscriminatorValue); },
        "timezone": n => { meProfileDto.timezone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicProfileDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicProfileDto(publicProfileDto: Partial<PublicProfileDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "avatarId": n => { publicProfileDto.avatarId = n.getGuidValue(); },
        "bio": n => { publicProfileDto.bio = n.getStringValue(); },
        "city": n => { publicProfileDto.city = n.getObjectValue<CityDto>(createCityDtoFromDiscriminatorValue); },
        "displayName": n => { publicProfileDto.displayName = n.getStringValue(); },
        "handle": n => { publicProfileDto.handle = n.getStringValue(); },
        "isVerified": n => { publicProfileDto.isVerified = n.getBooleanValue(); },
        "sports": n => { publicProfileDto.sports = n.getCollectionOfObjectValues<PublicUserSportDto>(createPublicUserSportDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicUserSportDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicUserSportDto(publicUserSportDto: Partial<PublicUserSportDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "footedness": n => { publicUserSportDto.footedness = n.getEnumValue<NullableOfFootedness>(NullableOfFootednessObject); },
        "heightCm": n => { publicUserSportDto.heightCm = n.getNumberValue(); },
        "isPrimary": n => { publicUserSportDto.isPrimary = n.getBooleanValue(); },
        "jerseyNumber": n => { publicUserSportDto.jerseyNumber = n.getNumberValue(); },
        "level": n => { publicUserSportDto.level = n.getEnumValue<SkillLevel>(SkillLevelObject); },
        "playingSince": n => { publicUserSportDto.playingSince = n.getNumberValue(); },
        "positions": n => { publicUserSportDto.positions = n.getCollectionOfObjectValues<UserSportPositionDto>(createUserSportPositionDtoFromDiscriminatorValue); },
        "sportEmoji": n => { publicUserSportDto.sportEmoji = n.getStringValue(); },
        "sportSlug": n => { publicUserSportDto.sportSlug = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SportDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSportDto(sportDto: Partial<SportDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "emoji": n => { sportDto.emoji = n.getStringValue(); },
        "hasPositions": n => { sportDto.hasPositions = n.getBooleanValue(); },
        "id": n => { sportDto.id = n.getGuidValue(); },
        "isTeamSport": n => { sportDto.isTeamSport = n.getBooleanValue(); },
        "nameI18n": n => { sportDto.nameI18n = n.getObjectValue<SportDto_nameI18n>(createSportDto_nameI18nFromDiscriminatorValue); },
        "slug": n => { sportDto.slug = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SportDto_nameI18n The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSportDto_nameI18n(sportDto_nameI18n: Partial<SportDto_nameI18n> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param TelegramAuthPayload The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTelegramAuthPayload(telegramAuthPayload: Partial<TelegramAuthPayload> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "auth_date": n => { telegramAuthPayload.authDate = n.getNumberValue(); },
        "first_name": n => { telegramAuthPayload.firstName = n.getStringValue(); },
        "hash": n => { telegramAuthPayload.hash = n.getStringValue(); },
        "id": n => { telegramAuthPayload.id = n.getNumberValue(); },
        "last_name": n => { telegramAuthPayload.lastName = n.getStringValue(); },
        "photo_url": n => { telegramAuthPayload.photoUrl = n.getStringValue(); },
        "username": n => { telegramAuthPayload.username = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateMeRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateMeRequest(updateMeRequest: Partial<UpdateMeRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "bio": n => { updateMeRequest.bio = n.getStringValue(); },
        "birthDate": n => { updateMeRequest.birthDate = n.getDateOnlyValue(); },
        "cityId": n => { updateMeRequest.cityId = n.getGuidValue(); },
        "displayName": n => { updateMeRequest.displayName = n.getStringValue(); },
        "gender": n => { updateMeRequest.gender = n.getEnumValue<NullableOfGender>(NullableOfGenderObject); },
        "handle": n => { updateMeRequest.handle = n.getStringValue(); },
        "locale": n => { updateMeRequest.locale = n.getStringValue(); },
        "phone": n => { updateMeRequest.phone = n.getStringValue(); },
        "profileVisibility": n => { updateMeRequest.profileVisibility = n.getEnumValue<NullableOfVisibility>(NullableOfVisibilityObject); },
        "timezone": n => { updateMeRequest.timezone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpsertUserSportRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsertUserSportRequest(upsertUserSportRequest: Partial<UpsertUserSportRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "footedness": n => { upsertUserSportRequest.footedness = n.getEnumValue<NullableOfFootedness>(NullableOfFootednessObject); },
        "heightCm": n => { upsertUserSportRequest.heightCm = n.getNumberValue(); },
        "isPrimary": n => { upsertUserSportRequest.isPrimary = n.getBooleanValue(); },
        "jerseyNumber": n => { upsertUserSportRequest.jerseyNumber = n.getNumberValue(); },
        "level": n => { upsertUserSportRequest.level = n.getEnumValue<SkillLevel>(SkillLevelObject); },
        "note": n => { upsertUserSportRequest.note = n.getStringValue(); },
        "playingSince": n => { upsertUserSportRequest.playingSince = n.getNumberValue(); },
        "positionIds": n => { upsertUserSportRequest.positionIds = n.getCollectionOfPrimitiveValues<Guid>("string"); },
        "primaryPositionId": n => { upsertUserSportRequest.primaryPositionId = n.getGuidValue(); },
        "visibility": n => { upsertUserSportRequest.visibility = n.getEnumValue<Visibility>(VisibilityObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param UserSportDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserSportDto(userSportDto: Partial<UserSportDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "footedness": n => { userSportDto.footedness = n.getEnumValue<NullableOfFootedness>(NullableOfFootednessObject); },
        "heightCm": n => { userSportDto.heightCm = n.getNumberValue(); },
        "isPrimary": n => { userSportDto.isPrimary = n.getBooleanValue(); },
        "jerseyNumber": n => { userSportDto.jerseyNumber = n.getNumberValue(); },
        "level": n => { userSportDto.level = n.getEnumValue<SkillLevel>(SkillLevelObject); },
        "note": n => { userSportDto.note = n.getStringValue(); },
        "playingSince": n => { userSportDto.playingSince = n.getNumberValue(); },
        "positions": n => { userSportDto.positions = n.getCollectionOfObjectValues<UserSportPositionDto>(createUserSportPositionDtoFromDiscriminatorValue); },
        "sportEmoji": n => { userSportDto.sportEmoji = n.getStringValue(); },
        "sportId": n => { userSportDto.sportId = n.getGuidValue(); },
        "sportSlug": n => { userSportDto.sportSlug = n.getStringValue(); },
        "visibility": n => { userSportDto.visibility = n.getEnumValue<Visibility>(VisibilityObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param UserSportPositionDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserSportPositionDto(userSportPositionDto: Partial<UserSportPositionDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { userSportPositionDto.code = n.getStringValue(); },
        "isPrimary": n => { userSportPositionDto.isPrimary = n.getBooleanValue(); },
        "positionId": n => { userSportPositionDto.positionId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param VenueDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVenueDto(venueDto: Partial<VenueDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "address": n => { venueDto.address = n.getStringValue(); },
        "distanceMeters": n => { venueDto.distanceMeters = n.getNumberValue(); },
        "id": n => { venueDto.id = n.getGuidValue(); },
        "lat": n => { venueDto.lat = n.getNumberValue(); },
        "lng": n => { venueDto.lng = n.getNumberValue(); },
        "name": n => { venueDto.name = n.getStringValue(); },
        "ratingAvg": n => { venueDto.ratingAvg = n.getNumberValue(); },
        "ratingCount": n => { venueDto.ratingCount = n.getNumberValue(); },
        "slug": n => { venueDto.slug = n.getStringValue(); },
    }
}
export interface MeProfileDto extends AdditionalDataHolder, Parsable {
    /**
     * The avatarId property
     */
    avatarId?: Guid | null;
    /**
     * The bio property
     */
    bio?: string | null;
    /**
     * The birthDate property
     */
    birthDate?: DateOnly | null;
    /**
     * The city property
     */
    city?: CityDto | null;
    /**
     * The displayName property
     */
    displayName?: string | null;
    /**
     * The gender property
     */
    gender?: NullableOfGender | null;
    /**
     * The handle property
     */
    handle?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The isVerified property
     */
    isVerified?: boolean | null;
    /**
     * The locale property
     */
    locale?: string | null;
    /**
     * The phone property
     */
    phone?: string | null;
    /**
     * The profileVisibility property
     */
    profileVisibility?: Visibility | null;
    /**
     * The sports property
     */
    sports?: UserSportDto[] | null;
    /**
     * The timezone property
     */
    timezone?: string | null;
}
export type NullableOfFootedness = (typeof NullableOfFootednessObject)[keyof typeof NullableOfFootednessObject];
export type NullableOfGender = (typeof NullableOfGenderObject)[keyof typeof NullableOfGenderObject];
export type NullableOfVisibility = (typeof NullableOfVisibilityObject)[keyof typeof NullableOfVisibilityObject];
export interface PublicProfileDto extends AdditionalDataHolder, Parsable {
    /**
     * The avatarId property
     */
    avatarId?: Guid | null;
    /**
     * The bio property
     */
    bio?: string | null;
    /**
     * The city property
     */
    city?: CityDto | null;
    /**
     * The displayName property
     */
    displayName?: string | null;
    /**
     * The handle property
     */
    handle?: string | null;
    /**
     * The isVerified property
     */
    isVerified?: boolean | null;
    /**
     * The sports property
     */
    sports?: PublicUserSportDto[] | null;
}
export interface PublicUserSportDto extends AdditionalDataHolder, Parsable {
    /**
     * The footedness property
     */
    footedness?: NullableOfFootedness | null;
    /**
     * The heightCm property
     */
    heightCm?: number | null;
    /**
     * The isPrimary property
     */
    isPrimary?: boolean | null;
    /**
     * The jerseyNumber property
     */
    jerseyNumber?: number | null;
    /**
     * The level property
     */
    level?: SkillLevel | null;
    /**
     * The playingSince property
     */
    playingSince?: number | null;
    /**
     * The positions property
     */
    positions?: UserSportPositionDto[] | null;
    /**
     * The sportEmoji property
     */
    sportEmoji?: string | null;
    /**
     * The sportSlug property
     */
    sportSlug?: string | null;
}
/**
 * Serializes information the current object
 * @param AuthResponseDto The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthResponseDto(writer: SerializationWriter, authResponseDto: Partial<AuthResponseDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authResponseDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("displayName", authResponseDto.displayName);
    writer.writeStringValue("handle", authResponseDto.handle);
    writer.writeGuidValue("userId", authResponseDto.userId);
    writer.writeAdditionalData(authResponseDto.additionalData);
}
/**
 * Serializes information the current object
 * @param CityDto The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCityDto(writer: SerializationWriter, cityDto: Partial<CityDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cityDto || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", cityDto.id);
    writer.writeNumberValue("lat", cityDto.lat);
    writer.writeNumberValue("lng", cityDto.lng);
    writer.writeObjectValue<CityDto_nameI18n>("nameI18n", cityDto.nameI18n, serializeCityDto_nameI18n);
    writer.writeStringValue("slug", cityDto.slug);
    writer.writeAdditionalData(cityDto.additionalData);
}
/**
 * Serializes information the current object
 * @param CityDto_nameI18n The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCityDto_nameI18n(writer: SerializationWriter, cityDto_nameI18n: Partial<CityDto_nameI18n> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cityDto_nameI18n || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(cityDto_nameI18n.additionalData);
}
/**
 * Serializes information the current object
 * @param CityDto2 The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCityDto2(writer: SerializationWriter, cityDto2: Partial<CityDto2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cityDto2 || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", cityDto2.id);
    writer.writeNumberValue("lat", cityDto2.lat);
    writer.writeNumberValue("lng", cityDto2.lng);
    writer.writeObjectValue<CityDto2_nameI18n>("nameI18n", cityDto2.nameI18n, serializeCityDto2_nameI18n);
    writer.writeStringValue("slug", cityDto2.slug);
    writer.writeAdditionalData(cityDto2.additionalData);
}
/**
 * Serializes information the current object
 * @param CityDto2_nameI18n The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCityDto2_nameI18n(writer: SerializationWriter, cityDto2_nameI18n: Partial<CityDto2_nameI18n> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cityDto2_nameI18n || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(cityDto2_nameI18n.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MeProfileDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMeProfileDto(writer: SerializationWriter, meProfileDto: Partial<MeProfileDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!meProfileDto || isSerializingDerivedType) { return; }
    writer.writeGuidValue("avatarId", meProfileDto.avatarId);
    writer.writeStringValue("bio", meProfileDto.bio);
    writer.writeDateOnlyValue("birthDate", meProfileDto.birthDate);
    writer.writeObjectValue<CityDto>("city", meProfileDto.city, serializeCityDto);
    writer.writeStringValue("displayName", meProfileDto.displayName);
    writer.writeEnumValue<NullableOfGender>("gender", meProfileDto.gender);
    writer.writeStringValue("handle", meProfileDto.handle);
    writer.writeGuidValue("id", meProfileDto.id);
    writer.writeBooleanValue("isVerified", meProfileDto.isVerified);
    writer.writeStringValue("locale", meProfileDto.locale);
    writer.writeStringValue("phone", meProfileDto.phone);
    writer.writeEnumValue<Visibility>("profileVisibility", meProfileDto.profileVisibility);
    writer.writeCollectionOfObjectValues<UserSportDto>("sports", meProfileDto.sports, serializeUserSportDto);
    writer.writeStringValue("timezone", meProfileDto.timezone);
    writer.writeAdditionalData(meProfileDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicProfileDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicProfileDto(writer: SerializationWriter, publicProfileDto: Partial<PublicProfileDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicProfileDto || isSerializingDerivedType) { return; }
    writer.writeGuidValue("avatarId", publicProfileDto.avatarId);
    writer.writeStringValue("bio", publicProfileDto.bio);
    writer.writeObjectValue<CityDto>("city", publicProfileDto.city, serializeCityDto);
    writer.writeStringValue("displayName", publicProfileDto.displayName);
    writer.writeStringValue("handle", publicProfileDto.handle);
    writer.writeBooleanValue("isVerified", publicProfileDto.isVerified);
    writer.writeCollectionOfObjectValues<PublicUserSportDto>("sports", publicProfileDto.sports, serializePublicUserSportDto);
    writer.writeAdditionalData(publicProfileDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicUserSportDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicUserSportDto(writer: SerializationWriter, publicUserSportDto: Partial<PublicUserSportDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicUserSportDto || isSerializingDerivedType) { return; }
    writer.writeEnumValue<NullableOfFootedness>("footedness", publicUserSportDto.footedness);
    writer.writeNumberValue("heightCm", publicUserSportDto.heightCm);
    writer.writeBooleanValue("isPrimary", publicUserSportDto.isPrimary);
    writer.writeNumberValue("jerseyNumber", publicUserSportDto.jerseyNumber);
    writer.writeEnumValue<SkillLevel>("level", publicUserSportDto.level);
    writer.writeNumberValue("playingSince", publicUserSportDto.playingSince);
    writer.writeCollectionOfObjectValues<UserSportPositionDto>("positions", publicUserSportDto.positions, serializeUserSportPositionDto);
    writer.writeStringValue("sportEmoji", publicUserSportDto.sportEmoji);
    writer.writeStringValue("sportSlug", publicUserSportDto.sportSlug);
    writer.writeAdditionalData(publicUserSportDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SportDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSportDto(writer: SerializationWriter, sportDto: Partial<SportDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!sportDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("emoji", sportDto.emoji);
    writer.writeBooleanValue("hasPositions", sportDto.hasPositions);
    writer.writeGuidValue("id", sportDto.id);
    writer.writeBooleanValue("isTeamSport", sportDto.isTeamSport);
    writer.writeObjectValue<SportDto_nameI18n>("nameI18n", sportDto.nameI18n, serializeSportDto_nameI18n);
    writer.writeStringValue("slug", sportDto.slug);
    writer.writeAdditionalData(sportDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SportDto_nameI18n The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSportDto_nameI18n(writer: SerializationWriter, sportDto_nameI18n: Partial<SportDto_nameI18n> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!sportDto_nameI18n || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(sportDto_nameI18n.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TelegramAuthPayload The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTelegramAuthPayload(writer: SerializationWriter, telegramAuthPayload: Partial<TelegramAuthPayload> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!telegramAuthPayload || isSerializingDerivedType) { return; }
    writer.writeNumberValue("auth_date", telegramAuthPayload.authDate);
    writer.writeStringValue("first_name", telegramAuthPayload.firstName);
    writer.writeStringValue("hash", telegramAuthPayload.hash);
    writer.writeNumberValue("id", telegramAuthPayload.id);
    writer.writeStringValue("last_name", telegramAuthPayload.lastName);
    writer.writeStringValue("photo_url", telegramAuthPayload.photoUrl);
    writer.writeStringValue("username", telegramAuthPayload.username);
    writer.writeAdditionalData(telegramAuthPayload.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateMeRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateMeRequest(writer: SerializationWriter, updateMeRequest: Partial<UpdateMeRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateMeRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("bio", updateMeRequest.bio);
    writer.writeDateOnlyValue("birthDate", updateMeRequest.birthDate);
    writer.writeGuidValue("cityId", updateMeRequest.cityId);
    writer.writeStringValue("displayName", updateMeRequest.displayName);
    writer.writeEnumValue<NullableOfGender>("gender", updateMeRequest.gender);
    writer.writeStringValue("handle", updateMeRequest.handle);
    writer.writeStringValue("locale", updateMeRequest.locale);
    writer.writeStringValue("phone", updateMeRequest.phone);
    writer.writeEnumValue<NullableOfVisibility>("profileVisibility", updateMeRequest.profileVisibility);
    writer.writeStringValue("timezone", updateMeRequest.timezone);
    writer.writeAdditionalData(updateMeRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpsertUserSportRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsertUserSportRequest(writer: SerializationWriter, upsertUserSportRequest: Partial<UpsertUserSportRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsertUserSportRequest || isSerializingDerivedType) { return; }
    writer.writeEnumValue<NullableOfFootedness>("footedness", upsertUserSportRequest.footedness);
    writer.writeNumberValue("heightCm", upsertUserSportRequest.heightCm);
    writer.writeBooleanValue("isPrimary", upsertUserSportRequest.isPrimary);
    writer.writeNumberValue("jerseyNumber", upsertUserSportRequest.jerseyNumber);
    writer.writeEnumValue<SkillLevel>("level", upsertUserSportRequest.level);
    writer.writeStringValue("note", upsertUserSportRequest.note);
    writer.writeNumberValue("playingSince", upsertUserSportRequest.playingSince);
    writer.writeCollectionOfPrimitiveValues<Guid>("positionIds", upsertUserSportRequest.positionIds);
    writer.writeGuidValue("primaryPositionId", upsertUserSportRequest.primaryPositionId);
    writer.writeEnumValue<Visibility>("visibility", upsertUserSportRequest.visibility);
    writer.writeAdditionalData(upsertUserSportRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UserSportDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserSportDto(writer: SerializationWriter, userSportDto: Partial<UserSportDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!userSportDto || isSerializingDerivedType) { return; }
    writer.writeEnumValue<NullableOfFootedness>("footedness", userSportDto.footedness);
    writer.writeNumberValue("heightCm", userSportDto.heightCm);
    writer.writeBooleanValue("isPrimary", userSportDto.isPrimary);
    writer.writeNumberValue("jerseyNumber", userSportDto.jerseyNumber);
    writer.writeEnumValue<SkillLevel>("level", userSportDto.level);
    writer.writeStringValue("note", userSportDto.note);
    writer.writeNumberValue("playingSince", userSportDto.playingSince);
    writer.writeCollectionOfObjectValues<UserSportPositionDto>("positions", userSportDto.positions, serializeUserSportPositionDto);
    writer.writeStringValue("sportEmoji", userSportDto.sportEmoji);
    writer.writeGuidValue("sportId", userSportDto.sportId);
    writer.writeStringValue("sportSlug", userSportDto.sportSlug);
    writer.writeEnumValue<Visibility>("visibility", userSportDto.visibility);
    writer.writeAdditionalData(userSportDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UserSportPositionDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserSportPositionDto(writer: SerializationWriter, userSportPositionDto: Partial<UserSportPositionDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!userSportPositionDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", userSportPositionDto.code);
    writer.writeBooleanValue("isPrimary", userSportPositionDto.isPrimary);
    writer.writeGuidValue("positionId", userSportPositionDto.positionId);
    writer.writeAdditionalData(userSportPositionDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param VenueDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVenueDto(writer: SerializationWriter, venueDto: Partial<VenueDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!venueDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("address", venueDto.address);
    writer.writeNumberValue("distanceMeters", venueDto.distanceMeters);
    writer.writeGuidValue("id", venueDto.id);
    writer.writeNumberValue("lat", venueDto.lat);
    writer.writeNumberValue("lng", venueDto.lng);
    writer.writeStringValue("name", venueDto.name);
    writer.writeNumberValue("ratingAvg", venueDto.ratingAvg);
    writer.writeNumberValue("ratingCount", venueDto.ratingCount);
    writer.writeStringValue("slug", venueDto.slug);
    writer.writeAdditionalData(venueDto.additionalData);
}
export type SkillLevel = (typeof SkillLevelObject)[keyof typeof SkillLevelObject];
export interface SportDto extends AdditionalDataHolder, Parsable {
    /**
     * The emoji property
     */
    emoji?: string | null;
    /**
     * The hasPositions property
     */
    hasPositions?: boolean | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The isTeamSport property
     */
    isTeamSport?: boolean | null;
    /**
     * The nameI18n property
     */
    nameI18n?: SportDto_nameI18n | null;
    /**
     * The slug property
     */
    slug?: string | null;
}
export interface SportDto_nameI18n extends AdditionalDataHolder, Parsable {
}
export interface TelegramAuthPayload extends AdditionalDataHolder, Parsable {
    /**
     * The auth_date property
     */
    authDate?: number | null;
    /**
     * The first_name property
     */
    firstName?: string | null;
    /**
     * The hash property
     */
    hash?: string | null;
    /**
     * The id property
     */
    id?: number | null;
    /**
     * The last_name property
     */
    lastName?: string | null;
    /**
     * The photo_url property
     */
    photoUrl?: string | null;
    /**
     * The username property
     */
    username?: string | null;
}
export interface UpdateMeRequest extends AdditionalDataHolder, Parsable {
    /**
     * The bio property
     */
    bio?: string | null;
    /**
     * The birthDate property
     */
    birthDate?: DateOnly | null;
    /**
     * The cityId property
     */
    cityId?: Guid | null;
    /**
     * The displayName property
     */
    displayName?: string | null;
    /**
     * The gender property
     */
    gender?: NullableOfGender | null;
    /**
     * The handle property
     */
    handle?: string | null;
    /**
     * The locale property
     */
    locale?: string | null;
    /**
     * The phone property
     */
    phone?: string | null;
    /**
     * The profileVisibility property
     */
    profileVisibility?: NullableOfVisibility | null;
    /**
     * The timezone property
     */
    timezone?: string | null;
}
export interface UpsertUserSportRequest extends AdditionalDataHolder, Parsable {
    /**
     * The footedness property
     */
    footedness?: NullableOfFootedness | null;
    /**
     * The heightCm property
     */
    heightCm?: number | null;
    /**
     * The isPrimary property
     */
    isPrimary?: boolean | null;
    /**
     * The jerseyNumber property
     */
    jerseyNumber?: number | null;
    /**
     * The level property
     */
    level?: SkillLevel | null;
    /**
     * The note property
     */
    note?: string | null;
    /**
     * The playingSince property
     */
    playingSince?: number | null;
    /**
     * The positionIds property
     */
    positionIds?: Guid[] | null;
    /**
     * The primaryPositionId property
     */
    primaryPositionId?: Guid | null;
    /**
     * The visibility property
     */
    visibility?: Visibility | null;
}
export interface UserSportDto extends AdditionalDataHolder, Parsable {
    /**
     * The footedness property
     */
    footedness?: NullableOfFootedness | null;
    /**
     * The heightCm property
     */
    heightCm?: number | null;
    /**
     * The isPrimary property
     */
    isPrimary?: boolean | null;
    /**
     * The jerseyNumber property
     */
    jerseyNumber?: number | null;
    /**
     * The level property
     */
    level?: SkillLevel | null;
    /**
     * The note property
     */
    note?: string | null;
    /**
     * The playingSince property
     */
    playingSince?: number | null;
    /**
     * The positions property
     */
    positions?: UserSportPositionDto[] | null;
    /**
     * The sportEmoji property
     */
    sportEmoji?: string | null;
    /**
     * The sportId property
     */
    sportId?: Guid | null;
    /**
     * The sportSlug property
     */
    sportSlug?: string | null;
    /**
     * The visibility property
     */
    visibility?: Visibility | null;
}
export interface UserSportPositionDto extends AdditionalDataHolder, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The isPrimary property
     */
    isPrimary?: boolean | null;
    /**
     * The positionId property
     */
    positionId?: Guid | null;
}
export interface VenueDto extends AdditionalDataHolder, Parsable {
    /**
     * The address property
     */
    address?: string | null;
    /**
     * The distanceMeters property
     */
    distanceMeters?: number | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lat property
     */
    lat?: number | null;
    /**
     * The lng property
     */
    lng?: number | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The ratingAvg property
     */
    ratingAvg?: number | null;
    /**
     * The ratingCount property
     */
    ratingCount?: number | null;
    /**
     * The slug property
     */
    slug?: string | null;
}
export type Visibility = (typeof VisibilityObject)[keyof typeof VisibilityObject];
export const NullableOfFootednessObject = {
    Left: "Left",
    Right: "Right",
    Both: "Both",
} as const;
export const NullableOfGenderObject = {
    Male: "Male",
    Female: "Female",
    Other: "Other",
} as const;
export const NullableOfVisibilityObject = {
    Public: "Public",
    Followers: "Followers",
    Private: "Private",
} as const;
export const SkillLevelObject = {
    Beginner: "Beginner",
    Amateur: "Amateur",
    Intermediate: "Intermediate",
    Advanced: "Advanced",
    SemiPro: "SemiPro",
    Pro: "Pro",
} as const;
export const VisibilityObject = {
    Public: "Public",
    Followers: "Followers",
    Private: "Private",
} as const;
/* tslint:enable */
/* eslint-enable */
