/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface CityDto extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lat property
     */
    lat?: number | null;
    /**
     * The lng property
     */
    lng?: number | null;
    /**
     * The nameI18n property
     */
    nameI18n?: CityDto_nameI18n | null;
    /**
     * The slug property
     */
    slug?: string | null;
}
export interface CityDto_nameI18n extends AdditionalDataHolder, Parsable {
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CityDto_nameI18n}
 */
// @ts-ignore
export function createCityDto_nameI18nFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCityDto_nameI18n;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CityDto}
 */
// @ts-ignore
export function createCityDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCityDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SportDto_nameI18n}
 */
// @ts-ignore
export function createSportDto_nameI18nFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSportDto_nameI18n;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SportDto}
 */
// @ts-ignore
export function createSportDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSportDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {VenueDto}
 */
// @ts-ignore
export function createVenueDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVenueDto;
}
/**
 * The deserialization information for the current model
 * @param CityDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCityDto(cityDto: Partial<CityDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { cityDto.id = n.getGuidValue(); },
        "lat": n => { cityDto.lat = n.getNumberValue(); },
        "lng": n => { cityDto.lng = n.getNumberValue(); },
        "nameI18n": n => { cityDto.nameI18n = n.getObjectValue<CityDto_nameI18n>(createCityDto_nameI18nFromDiscriminatorValue); },
        "slug": n => { cityDto.slug = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CityDto_nameI18n The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCityDto_nameI18n(cityDto_nameI18n: Partial<CityDto_nameI18n> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param SportDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSportDto(sportDto: Partial<SportDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "emoji": n => { sportDto.emoji = n.getStringValue(); },
        "hasPositions": n => { sportDto.hasPositions = n.getBooleanValue(); },
        "id": n => { sportDto.id = n.getGuidValue(); },
        "isTeamSport": n => { sportDto.isTeamSport = n.getBooleanValue(); },
        "nameI18n": n => { sportDto.nameI18n = n.getObjectValue<SportDto_nameI18n>(createSportDto_nameI18nFromDiscriminatorValue); },
        "slug": n => { sportDto.slug = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SportDto_nameI18n The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSportDto_nameI18n(sportDto_nameI18n: Partial<SportDto_nameI18n> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param VenueDto The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVenueDto(venueDto: Partial<VenueDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "address": n => { venueDto.address = n.getStringValue(); },
        "distanceMeters": n => { venueDto.distanceMeters = n.getNumberValue(); },
        "id": n => { venueDto.id = n.getGuidValue(); },
        "lat": n => { venueDto.lat = n.getNumberValue(); },
        "lng": n => { venueDto.lng = n.getNumberValue(); },
        "name": n => { venueDto.name = n.getStringValue(); },
        "ratingAvg": n => { venueDto.ratingAvg = n.getNumberValue(); },
        "ratingCount": n => { venueDto.ratingCount = n.getNumberValue(); },
        "slug": n => { venueDto.slug = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param CityDto The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCityDto(writer: SerializationWriter, cityDto: Partial<CityDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cityDto || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", cityDto.id);
    writer.writeNumberValue("lat", cityDto.lat);
    writer.writeNumberValue("lng", cityDto.lng);
    writer.writeObjectValue<CityDto_nameI18n>("nameI18n", cityDto.nameI18n, serializeCityDto_nameI18n);
    writer.writeStringValue("slug", cityDto.slug);
    writer.writeAdditionalData(cityDto.additionalData);
}
/**
 * Serializes information the current object
 * @param CityDto_nameI18n The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCityDto_nameI18n(writer: SerializationWriter, cityDto_nameI18n: Partial<CityDto_nameI18n> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cityDto_nameI18n || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(cityDto_nameI18n.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SportDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSportDto(writer: SerializationWriter, sportDto: Partial<SportDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!sportDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("emoji", sportDto.emoji);
    writer.writeBooleanValue("hasPositions", sportDto.hasPositions);
    writer.writeGuidValue("id", sportDto.id);
    writer.writeBooleanValue("isTeamSport", sportDto.isTeamSport);
    writer.writeObjectValue<SportDto_nameI18n>("nameI18n", sportDto.nameI18n, serializeSportDto_nameI18n);
    writer.writeStringValue("slug", sportDto.slug);
    writer.writeAdditionalData(sportDto.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SportDto_nameI18n The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSportDto_nameI18n(writer: SerializationWriter, sportDto_nameI18n: Partial<SportDto_nameI18n> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!sportDto_nameI18n || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(sportDto_nameI18n.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param VenueDto The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVenueDto(writer: SerializationWriter, venueDto: Partial<VenueDto> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!venueDto || isSerializingDerivedType) { return; }
    writer.writeStringValue("address", venueDto.address);
    writer.writeNumberValue("distanceMeters", venueDto.distanceMeters);
    writer.writeGuidValue("id", venueDto.id);
    writer.writeNumberValue("lat", venueDto.lat);
    writer.writeNumberValue("lng", venueDto.lng);
    writer.writeStringValue("name", venueDto.name);
    writer.writeNumberValue("ratingAvg", venueDto.ratingAvg);
    writer.writeNumberValue("ratingCount", venueDto.ratingCount);
    writer.writeStringValue("slug", venueDto.slug);
    writer.writeAdditionalData(venueDto.additionalData);
}
export interface SportDto extends AdditionalDataHolder, Parsable {
    /**
     * The emoji property
     */
    emoji?: string | null;
    /**
     * The hasPositions property
     */
    hasPositions?: boolean | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The isTeamSport property
     */
    isTeamSport?: boolean | null;
    /**
     * The nameI18n property
     */
    nameI18n?: SportDto_nameI18n | null;
    /**
     * The slug property
     */
    slug?: string | null;
}
export interface SportDto_nameI18n extends AdditionalDataHolder, Parsable {
}
export interface VenueDto extends AdditionalDataHolder, Parsable {
    /**
     * The address property
     */
    address?: string | null;
    /**
     * The distanceMeters property
     */
    distanceMeters?: number | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The lat property
     */
    lat?: number | null;
    /**
     * The lng property
     */
    lng?: number | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The ratingAvg property
     */
    ratingAvg?: number | null;
    /**
     * The ratingCount property
     */
    ratingCount?: number | null;
    /**
     * The slug property
     */
    slug?: string | null;
}
/* tslint:enable */
/* eslint-enable */
