/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithSportItemRequestBuilder, WithSportItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/me/sports
 */
export interface SportsRequestBuilder extends BaseRequestBuilder<SportsRequestBuilder> {
    /**
     * Gets an item from the game-org-api-client.api.me.sports.item collection
     * @param sportId Unique identifier of the item
     * @returns {WithSportItemRequestBuilder}
     */
     bySportId(sportId: Guid) : WithSportItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SportsRequestBuilderUriTemplate = "{+baseurl}/api/me/sports";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SportsRequestBuilderNavigationMetadata: Record<Exclude<keyof SportsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySportId: {
        requestsMetadata: WithSportItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["sportId"],
    },
};
/* tslint:enable */
/* eslint-enable */
