/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthResponseDtoFromDiscriminatorValue, serializeAuthResponseDto, serializeTelegramAuthPayload, type AuthResponseDto, type TelegramAuthPayload } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth/telegram
 */
export interface TelegramRequestBuilder extends BaseRequestBuilder<TelegramRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AuthResponseDto>}
     */
     post(body: TelegramAuthPayload, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AuthResponseDto | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: TelegramAuthPayload, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TelegramRequestBuilderUriTemplate = "{+baseurl}/api/auth/telegram";
/**
 * Metadata for all the requests in the request builder.
 */
export const TelegramRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TelegramRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createAuthResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeTelegramAuthPayload,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
