/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LogoutRequestBuilderRequestsMetadata, type LogoutRequestBuilder } from './logout/index.js';
// @ts-ignore
import { RefreshRequestBuilderRequestsMetadata, type RefreshRequestBuilder } from './refresh/index.js';
// @ts-ignore
import { TelegramRequestBuilderRequestsMetadata, type TelegramRequestBuilder } from './telegram/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The logout property
     */
    get logout(): LogoutRequestBuilder;
    /**
     * The refresh property
     */
    get refresh(): RefreshRequestBuilder;
    /**
     * The telegram property
     */
    get telegram(): TelegramRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/api/auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    logout: {
        requestsMetadata: LogoutRequestBuilderRequestsMetadata,
    },
    refresh: {
        requestsMetadata: RefreshRequestBuilderRequestsMetadata,
    },
    telegram: {
        requestsMetadata: TelegramRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
